version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm i -g typescript
      - echo "install nodejs"
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - echo "build complete"
  post_build:
    commands:
      - mkdir keys
      - aws s3 cp --region=us-east-2 "s3://dashboard-keys/public.key" "keys/" 
      - aws s3 cp --region=us-east-2 "s3://dashboard-keys/private.key" "keys/" 
artifacts:
  files:
  ##this will take all files within the dist folder which will then be zipped by CodeBuild then stored in S3
    - "**/*"
  base-directory: "."
  name: builds/build-$CODEBUILD_BUILD_NUMBER/dashboard-api-build
   