org: arhammusheer
app: dad-api
service: serverless-dad
provider:
  name: aws #Define the cloud provider to use
  runtime: nodejs14.x
  stage: dev
  region: us-east-2
functions:
  app:
    handler: dist/lambda.handler
    events: #Define the events that trigger the lambda
      - http: #Define an HTTP endpoint that respond to the / route
        path: /
        method: ANY #Define the HTTP methods to be used (GET/POST)
        cors: true
      - http: #Define an HTTP endpoin that respond to any routes
        path: /{proxy+}
        method: ANY
        cors: true
